# Use an official Nginx image to serve static content
FROM nginx:alpine

# Copy the static HTML file to the Nginx web directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80
